# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(
        build_number: latest_testflight_build_number + 1,
        xcodeproj: "golf.xcodeproj"
    )
    match(type: "appstore",
        git_full_name: 'Jules Burt',
        git_user_email: 'jburt@me.com')
    udid = sigh(output_path: "./provisions")

    gym(scheme: "golf", export_method: "app-store",
        clean: true)

    pilot(skip_waiting_for_build_processing: true)
  end

    after_all do |lane|
#       slack(
#           message: "Successfully deployed new App Update."
#       )
    end

    error do |lane, exception|
#       slack(
#           message: exception.message,
#           success: false
#       )
    end

end
