//
//  ScoreCardWorkerTests.swift
//  golf
//
//  Created by Jules Burt on 2018-06-02.
//  Copyright (c) 2018 bethegame Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import golf
import XCTest
/*
class ScoreCardWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ScoreCardWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupScoreCardWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupScoreCardWorker()
  {
    sut = ScoreCardWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testSomething()
  {
    // Given
    
    // When
    
    // Then
  }
}
 */
