//
//  ScoreCardInteractorTests.swift
//  golf
//
//  Created by Jules Burt on 2018-06-02.
//  Copyright (c) 2018 bethegame Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import golf
import XCTest

class ScoreCardInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ScoreCardInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupScoreCardInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupScoreCardInteractor()
  {
    sut = ScoreCardInteractor()
  }
  
  // MARK: Test doubles
  
    class ScoreCardPresentationLogicSpy: ScoreCardPresenterLogic {
        
        var presentScoreCardCalled:Bool = false
        func presentScoreCard(_ response: ScoreCard.getPlayerScoreCard.response) {
            presentScoreCardCalled = true
        }        
    }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = ScoreCardPresentationLogicSpy()
    sut.scoreCardPresenter = spy
    
    // When
    let request = ScoreCard.getPlayerScoreCard.request()
    sut.selectedPlayer = 1001
    sut.getPlayerScoreCard(request)
    
    // Then
    XCTAssertTrue(spy.presentScoreCardCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
